[package]
name = "velo_data"
version = "0.1.0"
edition = "2023"

[dependencies]
reqwest = { version = "0.11.22" , features = ["blocking"]}
base64 = "0.21.5"
polars = { version = "0.34.2" , features = ["describe", "is_in"]}
